### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by 999eagle** [mullvad/system-configuration-rs#20]
Hi,
do you think you could release a new version of `system-configuration` and `system-configuration-sys` on crates.io? I would like to use my recent additions in a crate, but I feel like a git dependency might be a bit tacky in a published crate. Thanks!

**Comment by 999eagle** [comment]
@faern friendly ping on this :)

**Comment by faern** [comment]
Sorry for the delay! I'll see if I can try to get it published soon!

**Comment by faern** [comment]
Upgrading it to Rust 2018 first (#21). General maintenance and upgrading.

**Comment by faern** [comment]
Here you go! https://crates.io/crates/system-configuration

Hope it works as intended :)
