### ISSUE TITLE
Memory Leak in `SCNetworkReachability::set_callback`

### ISSUE THREAD

**Issue by schultetwin1** [mullvad/system-configuration-rs#34]
I believe the following code in network_reachability.rs introduces a memory leak.

https://github.com/mullvad/system-configuration-rs/blob/1bc323a12552359f5e26b56d52aa29b3449c09ec/system-configuration/src/network_reachability.rs#L239-L254

`callback` is an `Arc` holding a `NetworkReachabilityCallbackContext`, which holds a reference counted `SCNetworkReachabability` object and the capture of the callback function. `callback` is then passed into `Arc::into_raw` but there is never a matching call to `Arc::from_raw`.

I believe we need to call `Arc::from_raw` once on that pointer to ensure that the memory allocated for `NetworkReachabilityCallbackContext::new` is freed.

**Comment by pronebird** [comment]
Hi,

Shouldn't `release_context` take care of that?

https://github.com/mullvad/system-configuration-rs/blob/1bc323a12552359f5e26b56d52aa29b3449c09ec/system-configuration/src/network_reachability.rs#L310-L314

**Comment by schultetwin1** [comment]
That's not my understanding on how [SCNetworkReachabilityContext](https://developer.apple.com/documentation/systemconfiguration/scnetworkreachabilitycontext?language=objc) works, but I could be wrong! 

From Apple's docs for the `release` function:

> The callback used to remove a retain previously added for the info field.

I'm assuming a "retain" refers to a call to the `retain` member of `SCNetworkReachabilityContext`. Our `retain` function adds a reference count to the `Arc`.

https://github.com/mullvad/system-configuration-rs/blob/1bc323a12552359f5e26b56d52aa29b3449c09ec/system-configuration/src/network_reachability.rs#L316-L323

 So `retain_context` will add a reference count to the `NetworkReachabilityCallbackContext` held in the `Arc` and `release_context` will remove that reference count.

To walk through the whole memory leak:

1. A user calls `SCNetworkReachability::set_callback`. 
2. This creates an `Arc<NetworkReachabilityCallbackContext>`. https://github.com/mullvad/system-configuration-rs/blob/1bc323a12552359f5e26b56d52aa29b3449c09ec/system-configuration/src/network_reachability.rs#L243
3. That `Arc` is the converted to a raw pointer. https://github.com/mullvad/system-configuration-rs/blob/1bc323a12552359f5e26b56d52aa29b3449c09ec/system-configuration/src/network_reachability.rs#L250
4. The Arc's reference count is now "1".
5. Retain / release functions are called incrementing the reference count up to 2 and then back to 1.
6. The `SCNetworkReachability` is dropped, but the reference count is still there because `into_raw` was called but the equivalent `from_raw` was never called.

**Comment by pronebird** [comment]
I think you are onto something here. I wrote a simple program in Objective-C to verify this behavior with debugger.

That's my observation:

1. `SCNetworkReachabilitySetCallback()` immediately calls `retain` on `info` member of `context` struct. This `retain` is later balanced with a `release` call upon release of `SCNetworkReachabilityRef` (i.e via `CFRelease()`).
2. Each call reachability callback is preceded by a call to `retain` and then followed by the call to `release` after callback invocation.

So in short, I think the solution is to simply lower the ref count by 1 after the call to `SCNetworkReachabilitySetCallback()`.

```rs
unsafe {
    _ = Arc::from_raw(callback_ptr as *mut Self);
}
```

Also retain and release functions can be simplified by using `decrement_strong_count` and `increment_strong_count` but not sure maybe there is some sense in all that juggling that's going on in `retain_context`.

```rs
extern "C" fn release_context(ctx: *const c_void) {
    unsafe {
        Arc:: decrement_strong_count(ctx as *mut Self);
    }
}

extern "C" fn retain_context(ctx_ptr: *const c_void) -> *const c_void {
    unsafe {
        Arc:: increment_strong_count(ctx_ptr as *const Self);
        ctx_ptr
    }
}
```

**Comment by schultetwin1** [comment]
Using a debugger in Objective-C was a good idea! Thanks for doing that.

I also looked at the [source code for `SCNetworkReachabilitySetCallback`](https://opensource.apple.com/source/configd/configd-1109.60.2/SystemConfiguration.fproj/SCNetworkReachability.c.auto.html) and it looks like the `retain` callback is guaranteed to be called as long as it's not null. 

```c
if (context->retain != NULL) {
    targetPrivate->rlsContext.info = (void *)(*context->retain)(context->info);
}
```

Which just further confirms what you saw in the debugger.

Looking back through the history of configd releases, it looks like this was always the case (so we aren't breaking any older versions of macOS). The same is true with the `CFRelease` call, which you also saw in the debugger.

```c
if (targetPrivate->rlsContext.release != NULL) {
    (*targetPrivate->rlsContext.release)(targetPrivate->rlsContext.info);
}
```

> I think the solution is to simply lower the ref count by 1 after the call to SCNetworkReachabilitySetCallback()

That sounds like a good idea to me!

I also like the increment/decrement strong count idea. I didn't know that existed.

I'll make those changes.

**Comment by schultetwin1** [comment]
Ah crap, I see you already created a PR as well. Sorry I missed that. I'm happy with either solution.

**Comment by pronebird** [comment]
@schultetwin1 all good. The use of `Arc::as_ptr()` is better than my `Arc::into_raw() + Arc::from_raw()` round trip. Also you left an elaborate comment in there, so I am closing my PR in favour of yours. Good work 👍
