### ISSUE TITLE
Include license files in crates

### ISSUE THREAD

**Issue by jwodder** [mullvad/system-configuration-rs#44]
Currently, the `LICENSE-APACHE` and `LICENSE-MIT` files at the root of this repository are not included in the `system-configuration` and `system-configuration-sys` crates uploaded to crates.io, which is a problem for dependents who wish to properly honor licensing requirements.  I believe that, in order to include them in the crates, it's necessary to copy the license files into the individual package roots (i.e., next to the `Cargo.toml` files).

**Comment by faern** [comment]
Both our crates specify the license name in the `license` header. Is that not enough? They are both well known standard licenses, so the actual license text should not be needed as that's given from their names.

**Comment by faern** [comment]
The Cargo manual has this to say:

> If a package is using a nonstandard license, then the license-file field may be specified in lieu of the license field.

-- https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

So it does not really sound like it encourages license files to begin with. We do specify what license the crate is under already. And tools such as `cargo deny` etc do pick it up properly already

**Comment by jwodder** [comment]
@faern 

* Most of the tools I know of for gathering licenses of Rust dependencies (specifically, [`cargo-bundle-licenses`](https://github.com/sstadick/cargo-bundle-licenses) and [`cargo-lichking`](https://github.com/Nemo157/cargo-lichking), but not [`cargo-about`](https://github.com/EmbarkStudios/cargo-about)) are not able to substitute standard texts for missing licenses.

* While an argument could be made that the Apache 2.0 license can be filled in automatically, the MIT license cannot, as it includes a copyright date and author name specific to the project.  Indeed, [`LICENSE-MIT`](https://github.com/mullvad/system-configuration-rs/blob/main/LICENSE-MIT) in this repository starts with "Copyright (c) 2017 Amagicom AB", and the license itself requires that "The above copyright notice ... shall be included in all copies or substantial portions of the Software." — which affects anyone distributing a binary executable built with one of these crates as a dependency.

**Comment by jwodder** [comment]
@faern I'm not asking you to use the `license-file` field; I'm asking you to include the license files themselves in the crates uploaded to crates.io, which you can do by just putting them inside the crates' source directories.

**Comment by faern** [comment]
Fixed in #46! Thanks for reporting. This was indeed easily fixed. If tools use it then it's just good :+1:
